main:
# # leg main
#   force z (leg):
#     legends:
#       - { key: ast_tgtrlegWrenchOut, id: [2] }
#       - { key: ast_actrlegWrenchOut, id: [2] }
#       - { key: ast_tgtllegWrenchOut, id: [2] }
#       - { key: ast_actllegWrenchOut, id: [2] }
#     bottom_label:
#     newline: false

#   moment xy (leg):
#     legends:
#       - { key: ast_tgtrlegWrenchOut, id: [3-4] }
#       - { key: ast_actrlegWrenchOut, id: [3-4] }
#       - { key: ast_tgtllegWrenchOut, id: [3-4] }
#       - { key: ast_actllegWrenchOut, id: [3-4] }
#     bottom_label:
#     newline: false

# # leg sub
#   force xy (leg):
#     legends:
#       - { key: ast_tgtrlegWrenchOut, id: [0-1] }
#       - { key: ast_actrlegWrenchOut, id: [0-1] }
#       - { key: ast_tgtllegWrenchOut, id: [0-1] }
#       - { key: ast_actllegWrenchOut, id: [0-1] }
#     bottom_label:
#     newline: false

#   moment z (leg):
#     legends:
#       - { key: ast_tgtrlegWrenchOut, id: [5] }
#       - { key: ast_actrlegWrenchOut, id: [5] }
#       - { key: ast_tgtllegWrenchOut, id: [5] }
#       - { key: ast_actllegWrenchOut, id: [5] }
#     bottom_label:

  rleg_q:
    legends:
      - { key: ast_q, id: [0-5] }
      - { key: RobotHardware0_q, id: [0-5] }
      - { key: el_q, id: [0-5] }

  lleg_q:
    legends:
      - { key: ast_q, id: [6-11] }
      - { key: RobotHardware0_q, id: [6-11] }
      - { key: el_q, id: [6-11] }

#   rleg_dq:
#     legends:
#       - { key: RobotHardware0_dq, id: [0-5] }

  rleg_Torque:
    legends:
      - { key: torque, id: [0-5] }

  lleg_Torque:
    legends:
      - { key: torque, id: [6-11] }

  rleg_servo_state:
    legends:
      - { key: ServoState, id: [0-5] }

  lleg_servo_state:
    legends:
      - { key: ServoState, id: [6-11] }

  rleg_watt:
    legends:
      - { key: watt, id: [0-5] }

  lleg_watt:
    legends:
      - { key: watt, id: [6-11] }
